name: Build Electron App

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-client/**'
      - '.github/workflows/build-electron.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web-client/**'
      - '.github/workflows/build-electron.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: web-client/package-lock.json

      - name: Install dependencies
        run: |
          cd web-client
          npm ci

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd web-client
          npm run electron:build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build for macOS (Universal)
        if: matrix.os == 'macos-latest'
        run: |
          cd web-client
          npm run electron:build:mac:universal
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: electron-windows
          path: |
            web-client/dist-electron/*.exe
            web-client/dist-electron/*.exe.blockmap
          retention-days: 30

      - name: Upload macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: electron-macos
          path: |
            web-client/dist-electron/*.dmg
            web-client/dist-electron/*.dmg.blockmap
          retention-days: 30
