name: Build STM32 MCU Firmware

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mcu/**'
      - '.github/workflows/build-mcu.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mcu/**'
      - '.github/workflows/build-mcu.yml'

jobs:
  build-stm32:
    name: Build STM32F103 Firmware
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        config:
          - name: "Debug Build"
            build_type: "Debug"
            debug: 1
          - name: "Release Build"
            build_type: "Release"
            debug: 0
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install ARM Toolchain and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-none-eabi \
          binutils-arm-none-eabi \
          libnewlib-arm-none-eabi \
          libstdc++-arm-none-eabi-newlib \
          ninja-build \
          cmake \
          build-essential

    - name: Verify Toolchain Installation
      run: |
        arm-none-eabi-gcc --version
        arm-none-eabi-objcopy --version
        ninja --version
        cmake --version
        # Test compilation of a simple program
        echo 'int main() { return 0; }' > test.c
        arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -c test.c -o test.o
        rm -f test.c test.o

    - name: Set Build Environment
      run: |
        echo "BUILD_TYPE=${{ matrix.config.build_type }}" >> $GITHUB_ENV

    - name: Build Firmware
      working-directory: mcu
      run: |
        ./cmake-build.sh build ${{ matrix.config.build_type }}

    - name: Check Build Artifacts
      working-directory: mcu/chis_flash_burner
      run: |
        echo "Build artifacts for ${{ matrix.config.build_type }}:"
        ls -la build/${{ matrix.config.build_type }}/ || echo "No build directory found"
        if [ -f "build/${{ matrix.config.build_type }}/chis_flash_burner.elf" ]; then
          echo "=== Size Information ==="
          arm-none-eabi-size build/${{ matrix.config.build_type }}/chis_flash_burner.elf
          echo "=== Section Headers ==="
          arm-none-eabi-objdump -h build/${{ matrix.config.build_type }}/chis_flash_burner.elf
        fi

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: stm32-firmware-${{ matrix.config.build_type }}-${{ github.sha }}
        path: |
          mcu/chis_flash_burner/build/${{ matrix.config.build_type }}/*.elf
          mcu/chis_flash_burner/build/${{ matrix.config.build_type }}/*.hex
          mcu/chis_flash_burner/build/${{ matrix.config.build_type }}/*.bin
          mcu/chis_flash_burner/build/${{ matrix.config.build_type }}/*.map
        retention-days: 30

    - name: Archive Build Logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.config.build_type }}-${{ github.sha }}
        path: |
          mcu/chis_flash_burner/build/${{ matrix.config.build_type }}/*.lst
        retention-days: 7

  # Static analysis job
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-format

    - name: Run CPPCheck
      working-directory: mcu/chis_flash_burner
      run: |
        cppcheck --enable=all --force --xml --xml-version=2 \
          --suppress=missingIncludeSystem \
          --suppress=unusedFunction \
          --suppress=unmatchedSuppression \
          Core/Src/ 2> cppcheck-report.xml || true

    - name: Check Code Format
      working-directory: mcu/chis_flash_burner
      run: |
        echo "Checking code formatting..."
        find Core/Src -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror || {
          echo "Code formatting issues found. Please run clang-format on your code."
          exit 1
        }

    - name: Upload Analysis Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: static-analysis-${{ github.sha }}
        path: |
          mcu/chis_flash_burner/cppcheck-report.xml
        retention-days: 7

  # Security scan job
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/c
